// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pos.proto
#ifndef GRPC_pos_2eproto__INCLUDED
#define GRPC_pos_2eproto__INCLUDED

#include "pos.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace pos {

class PosServicer final {
 public:
  static constexpr char const* service_full_name() {
    return "pos.PosServicer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // easy call
    virtual ::grpc::Status EasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::pos::EasyCallReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::EasyCallReply>> AsyncEasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::EasyCallReply>>(AsyncEasyCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::EasyCallReply>> PrepareAsyncEasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::EasyCallReply>>(PrepareAsyncEasyCallRaw(context, request, cq));
    }
    // client stream
    virtual ::grpc::Status PosCall(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::pos::PosReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::PosReply>> AsyncPosCall(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::PosReply>>(AsyncPosCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::PosReply>> PrepareAsyncPosCall(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pos::PosReply>>(PrepareAsyncPosCallRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // easy call
      virtual void EasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest* request, ::pos::EasyCallReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest* request, ::pos::EasyCallReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // client stream
      virtual void PosCall(::grpc::ClientContext* context, const ::pos::PosRequest* request, ::pos::PosReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PosCall(::grpc::ClientContext* context, const ::pos::PosRequest* request, ::pos::PosReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pos::EasyCallReply>* AsyncEasyCallRaw(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pos::EasyCallReply>* PrepareAsyncEasyCallRaw(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pos::PosReply>* AsyncPosCallRaw(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pos::PosReply>* PrepareAsyncPosCallRaw(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status EasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::pos::EasyCallReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::EasyCallReply>> AsyncEasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::EasyCallReply>>(AsyncEasyCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::EasyCallReply>> PrepareAsyncEasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::EasyCallReply>>(PrepareAsyncEasyCallRaw(context, request, cq));
    }
    ::grpc::Status PosCall(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::pos::PosReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::PosReply>> AsyncPosCall(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::PosReply>>(AsyncPosCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::PosReply>> PrepareAsyncPosCall(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pos::PosReply>>(PrepareAsyncPosCallRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void EasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest* request, ::pos::EasyCallReply* response, std::function<void(::grpc::Status)>) override;
      void EasyCall(::grpc::ClientContext* context, const ::pos::EasyCallRequest* request, ::pos::EasyCallReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PosCall(::grpc::ClientContext* context, const ::pos::PosRequest* request, ::pos::PosReply* response, std::function<void(::grpc::Status)>) override;
      void PosCall(::grpc::ClientContext* context, const ::pos::PosRequest* request, ::pos::PosReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pos::EasyCallReply>* AsyncEasyCallRaw(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pos::EasyCallReply>* PrepareAsyncEasyCallRaw(::grpc::ClientContext* context, const ::pos::EasyCallRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pos::PosReply>* AsyncPosCallRaw(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pos::PosReply>* PrepareAsyncPosCallRaw(::grpc::ClientContext* context, const ::pos::PosRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_EasyCall_;
    const ::grpc::internal::RpcMethod rpcmethod_PosCall_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // easy call
    virtual ::grpc::Status EasyCall(::grpc::ServerContext* context, const ::pos::EasyCallRequest* request, ::pos::EasyCallReply* response);
    // client stream
    virtual ::grpc::Status PosCall(::grpc::ServerContext* context, const ::pos::PosRequest* request, ::pos::PosReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_EasyCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EasyCall() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_EasyCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EasyCall(::grpc::ServerContext* /*context*/, const ::pos::EasyCallRequest* /*request*/, ::pos::EasyCallReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEasyCall(::grpc::ServerContext* context, ::pos::EasyCallRequest* request, ::grpc::ServerAsyncResponseWriter< ::pos::EasyCallReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PosCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PosCall() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PosCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PosCall(::grpc::ServerContext* /*context*/, const ::pos::PosRequest* /*request*/, ::pos::PosReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPosCall(::grpc::ServerContext* context, ::pos::PosRequest* request, ::grpc::ServerAsyncResponseWriter< ::pos::PosReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_EasyCall<WithAsyncMethod_PosCall<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_EasyCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EasyCall() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pos::EasyCallRequest, ::pos::EasyCallReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pos::EasyCallRequest* request, ::pos::EasyCallReply* response) { return this->EasyCall(context, request, response); }));}
    void SetMessageAllocatorFor_EasyCall(
        ::grpc::MessageAllocator< ::pos::EasyCallRequest, ::pos::EasyCallReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pos::EasyCallRequest, ::pos::EasyCallReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EasyCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EasyCall(::grpc::ServerContext* /*context*/, const ::pos::EasyCallRequest* /*request*/, ::pos::EasyCallReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EasyCall(
      ::grpc::CallbackServerContext* /*context*/, const ::pos::EasyCallRequest* /*request*/, ::pos::EasyCallReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PosCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PosCall() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::pos::PosRequest, ::pos::PosReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pos::PosRequest* request, ::pos::PosReply* response) { return this->PosCall(context, request, response); }));}
    void SetMessageAllocatorFor_PosCall(
        ::grpc::MessageAllocator< ::pos::PosRequest, ::pos::PosReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pos::PosRequest, ::pos::PosReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PosCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PosCall(::grpc::ServerContext* /*context*/, const ::pos::PosRequest* /*request*/, ::pos::PosReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PosCall(
      ::grpc::CallbackServerContext* /*context*/, const ::pos::PosRequest* /*request*/, ::pos::PosReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_EasyCall<WithCallbackMethod_PosCall<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_EasyCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EasyCall() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_EasyCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EasyCall(::grpc::ServerContext* /*context*/, const ::pos::EasyCallRequest* /*request*/, ::pos::EasyCallReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PosCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PosCall() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PosCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PosCall(::grpc::ServerContext* /*context*/, const ::pos::PosRequest* /*request*/, ::pos::PosReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_EasyCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EasyCall() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_EasyCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EasyCall(::grpc::ServerContext* /*context*/, const ::pos::EasyCallRequest* /*request*/, ::pos::EasyCallReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEasyCall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PosCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PosCall() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PosCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PosCall(::grpc::ServerContext* /*context*/, const ::pos::PosRequest* /*request*/, ::pos::PosReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPosCall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EasyCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EasyCall() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EasyCall(context, request, response); }));
    }
    ~WithRawCallbackMethod_EasyCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EasyCall(::grpc::ServerContext* /*context*/, const ::pos::EasyCallRequest* /*request*/, ::pos::EasyCallReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EasyCall(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PosCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PosCall() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PosCall(context, request, response); }));
    }
    ~WithRawCallbackMethod_PosCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PosCall(::grpc::ServerContext* /*context*/, const ::pos::PosRequest* /*request*/, ::pos::PosReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PosCall(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EasyCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EasyCall() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pos::EasyCallRequest, ::pos::EasyCallReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pos::EasyCallRequest, ::pos::EasyCallReply>* streamer) {
                       return this->StreamedEasyCall(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EasyCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EasyCall(::grpc::ServerContext* /*context*/, const ::pos::EasyCallRequest* /*request*/, ::pos::EasyCallReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEasyCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pos::EasyCallRequest,::pos::EasyCallReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PosCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PosCall() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pos::PosRequest, ::pos::PosReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pos::PosRequest, ::pos::PosReply>* streamer) {
                       return this->StreamedPosCall(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PosCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PosCall(::grpc::ServerContext* /*context*/, const ::pos::PosRequest* /*request*/, ::pos::PosReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPosCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pos::PosRequest,::pos::PosReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_EasyCall<WithStreamedUnaryMethod_PosCall<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_EasyCall<WithStreamedUnaryMethod_PosCall<Service > > StreamedService;
};

}  // namespace pos


#endif  // GRPC_pos_2eproto__INCLUDED
